[build]
  command = "npm run build"
  dir = "out"  # Set this to the directory where your static build files are generated

[workers.dev]
  route = "/*"

[[headers]]
  path = "/*"
  headers = [
    { key = "ngrok-skip-browser-warning", value = "true" }
  ]
  
